### ISSUE TITLE
Check script 'main.nf' at line: 267

### ISSUE THREAD

**Issue by yangchuhua** [eQTL-Catalogue/rnaseq#2]
To Whom It May Concern:

your pipeline is awesome. Thanks for all your effort in this job.

When I ran pipeline by the following commands I got the error report that "No such variable: readPaths--- Check script 'main.nf' at line: 267 or see '.nextflow.log' file for more details "
$ /raid3/homedirs/yang/software/nextflow run /raid3/homedirs/yang/software/rnaseq/main.nf \
>   --readPathFile ../test.fastq.filePath  \
>   -profile docker \
>   --genomes GRCh38 \
>   --singleEnd true \
>   --aligner 'star'  \
>   --star_index ../hg38_genocode_v26_primary_star_index_sjdbOverhang149  \
>   --fastq  ../GRCh38.p10.genome.fa  \
>   --gff ../gencode.v26.chr_patch_hapl_scaff.annotation.gff3  \
>   --run_salmon false  \
>   --run_txrevise false \
>   --run_exon_quant fasle \
>   --run_tx_exp_quant false \
>   --run_leafcutter true \
>   --skip_qc true \
>   --skip_multiqc true \
>   --skip_edger true  \
>   --skip_alignment false

N E X T F L O W  ~  version 21.04.3
Launching `../rnaseq/main.nf` [prickly_hamilton] - revision: 4e88dccf0e
No such variable: readPaths
 -- Check script 'main.nf' at line: 267 or see '.nextflow.log' file for more details

I wonder if the "readPaths" is the parameter "--reads" in your main.nf.

Best,
Chuhua

**Comment by kauralasoo** [comment]
Hi Chuhua,

I think you have a small typo in your command. The name of the parameter should be --readPath**s**File, not --readPathFile.

We have some more instructions here:
https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/master/tutorials/workflow_execution.md

Best,
Kaur

**Comment by yangchuhua** [comment]
> Hi Chuhua,
> 
> I think you have a small typo in your command. The name of the parameter should be --readPath**s**File, not --readPathFile.
> 
> We have some more instructions here:
> https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/master/tutorials/workflow_execution.md
> 
> Best,
> Kaur

Hi Kaur,

Thank you very, very much! It really was a typo.

Thank you for sharing the link. It was very helpful!

Best,
Chuhua
