### ISSUE TITLE
Include Statement Problem in Nextflow Workflow

### ISSUE THREAD

**Issue by pinunQ** [eQTL-Catalogue/rnaseq#5]
Whenever I am trying to run the rnaseq pipeline I recieve an error that says the `Include statement is not allowed within a workflow definition` 

I checked about this error on Nextflow github but there is no stable solution provided and with my limited knowledge in Nextflow I am unable to resolve it.

Command used to run - 

`nextflow run main.nf -profile test`
`#nextflow run main.nf -profile conda,test`

Version Info - 
`N E X T F L O W  ~  version 21.10.6`
`Java Version - openjdk 11.0.1-internal 2018-10-16`

Log File- 
[nextflow_log.txt](https://github.com/eQTL-Catalogue/rnaseq/files/8485902/nextflow_log.txt)

**Comment by kauralasoo** [comment]
Sorry, I missed this earlier. Should now be fixed in the latest release: https://github.com/eQTL-Catalogue/rnaseq/releases/tag/v22.05.1
